# Generated by Django 5.1.3 on 2024-11-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('product_description', models.CharField(max_length=1000, null=True)),
                ('no_product_orders', models.PositiveIntegerField(null=True)),
                ('product_rating', models.PositiveSmallIntegerField(null=True)),
                ('product_image', models.URLField(null=True)),
            ],
        ),
    ]
