# Generated by Django 5.1.3 on 2024-11-17 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product_card', '0002_product_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='no_product_orders',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_rating',
        ),
    ]
