# Generated by Django 5.1.3 on 2024-11-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product_card', '0004_product_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='engine_size',
            field=models.FloatField(default=0.0, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='transmission',
            field=models.CharField(choices=[('mechanics', 'Mechanics'), ('automatic', 'Automatic')], default='mechanics', max_length=12),
        ),
    ]
