# Generated by Django 5.1.3 on 2024-11-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product_card', '0005_product_engine_size_alter_product_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='drive',
            field=models.CharField(choices=[('front_wheel_drive', 'Передний привод'), ('rear_wheel_drive', 'Задний привод'), ('4WD', 'Полный привод')], default='front_wheel_drive', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='transmission',
            field=models.CharField(choices=[('mechanics', 'Mechanics'), ('automatic', 'Automatic')], default='mechanics', max_length=15),
        ),
    ]
