# Generated by Django 5.1.3 on 2024-11-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product_card', '0007_product_color_product_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='drive',
            field=models.CharField(choices=[('front_wheel_drive', 'Передний привод'), ('Задний привод', 'rear_wheel_drive'), ('4WD', 'Полный привод')], default='front_wheel_drive', max_length=20),
        ),
    ]
