# Generated by Django 5.1.3 on 2024-11-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product_card', '0008_alter_product_drive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='drive',
            field=models.CharField(choices=[('Передний привод', 'front_wheel_drive'), ('Задний привод', 'rear_wheel_drive'), ('Полный привод', '4WD')], default='Задний привод', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='transmission',
            field=models.CharField(choices=[('Механика', 'Mechanics'), ('Автомат', 'Automatic')], default='Mechanics', max_length=15),
        ),
    ]
